version: '3.3'
services:
  haproxy:
    #image: haproxy:2.2.8 # We need to update the settings in order to update to the current LTS
    image: haproxy:2.0.12
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    dns_search:
      - abtlus.org.br
    dns:
      - 10.0.0.71
      - 10.0.0.72
    volumes:
      - /storage/services/repository/docker-stacks/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /storage/services/repository/docker-stacks/haproxy/haproxy.pem:/etc/ssl/haproxy.pem
    logging:
      driver: "json-file"
      options:
        max-file: "4"
        max-size: "250m"
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname != CA-RaTim-CO-IOCSrv
          - node.hostname != IA-14RaDiag03-CO-IOCSrv
          - node.hostname != IA-16RaBbB-CO-IOCSrv
          - node.hostname != IA-18RaDiag04-CO-IOCSrv
          - node.hostname != IA-20RaDiag01-CO-IOCSrv-1
          - node.hostname != IA-20RaDiag01-CO-IOCSrv-2
          - node.hostname != IA-20RaDiag02-CO-IOCSrv-1
          - node.hostname != IA-20RaDiag02-CO-IOCSrv-2
