version: '2'
services:
    con-haproxy:
        container_name: lnls-haproxy
        image: haproxy:latest
        ports:
            - "443:443"
            - "8080:8080"
            - "80:80"
        dns:
            - 10.0.0.71
            - 10.0.0.72
        volumes:
            - /etc/systemd/system/lnls-haproxy.service.d/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
            - /etc/systemd/system/lnls-haproxy.service.d/haproxy.pem:/etc/ssl/haproxy.pem
        logging:
            driver: "json-file"
            options:
                max-file: "4"
                max-size: "250m"
        
