version: '3.6'

x-defaults: &defaults
  image: dockerregistry.lnls-sirius.com.br/haproxy:2.2
  dns:
    - 10.0.0.71
    - 10.0.0.72
  dns_search:
      - abtlus.org.br
  logging:
    driver: "json-file"
    options:
      max-file: "4"
      max-size: "250m"
  networks:
    - host_network

networks:
  host_network:
    external:
      name: "host"

services:
  ta:
    <<: *defaults
    volumes:
      - /storage/services/repository/docker-stacks/Haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /storage/services/repository/docker-stacks/Haproxy/ssl-ta/haproxy.pem:/etc/ssl/haproxy.pem
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == TA-TiRack-CO-FWSrv-1
  ca:
    <<: *defaults
    volumes:
      - /storage/services/repository/docker-stacks/Haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /storage/services/repository/docker-stacks/Haproxy/ssl-ca/haproxy.pem:/etc/ssl/haproxy.pem
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == CA-RaCtrl-CO-Srv-1
  la:
    <<: *defaults
    image: dockerregistry.lnls-sirius.com.br/haproxy:2.2
    volumes:
      - /storage/services/repository/docker-stacks/Haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /storage/services/repository/docker-stacks/Haproxy/ssl-la/haproxy.pem:/etc/ssl/haproxy.pem
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == LA-RaCtrl-CO-Srv-1
