version: '3.3'
services:
  con-haproxy:
    container_name: lnls-haproxy
    image: haproxy:2.0.12
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
    dns_search:
      - abtlus.org.br
    dns:
      - 10.0.0.71
      - 10.0.0.72
    volumes:
      - /home/con-srv/LA-disk0/repository/docker-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/systemd/system/lnls-haproxy.service.d/haproxy.pem:/etc/ssl/haproxy.pem
    logging:
      driver: "json-file"
      options:
        max-file: "4"
        max-size: "250m"
    deploy:
      mode: global
